services:
  hldk:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    volumes:
      - hldk_data:/app/data
    env_file:
      - ../.env
    depends_on:
      - chroma

  chroma:
    image: chromadb/chroma:latest
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
    ports:
      - 8000:8000
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  hldk_data:
    driver: local
  chroma_data:
    driver: local