ALTER TABLE requests ADD COLUMN filesChanged INTEGER DEFAULT 0;
ALTER TABLE requests ADD COLUMN insertions INTEGER DEFAULT 0;
ALTER TABLE requests ADD COLUMN deletions INTEGER DEFAULT 0;
ALTER TABLE requests ADD COLUMN testFilesChanged INTEGER DEFAULT 0;
ALTER TABLE requests ADD COLUMN testInsertions INTEGER DEFAULT 0;
ALTER TABLE requests ADD COLUMN testDeletions INTEGER DEFAULT 0;